//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.Physicians = new HashSet<Physician>();
        }
    
        public string speciality1 { get; set; }
        public int spec_id { get; set; }
    
        public virtual ICollection<Physician> Physicians { get; set; }
    }
}
