//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public Hospital()
        {
            this.Physicians = new HashSet<Physician>();
        }
    
        public int Id { get; set; }
        public string HospitalName { get; set; }
    
        public virtual ICollection<Physician> Physicians { get; set; }
    }
}
