//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Physician
    {
        

        public int id { get; set; }
        [Required]
       [RegularExpression(@"[a-zA-Z0-9]*", ErrorMessage = "NPI CONTAINS ALPHABETS AND NUMBERS ")]
        public string Npi { get; set; }
        [Required]
        [RegularExpression(@"[a-zA-Z\s]*", ErrorMessage = "NAME CONTAINS ONLY ALPHABET")]
        public string Name { get; set; }
        [Required]
        [Range(25, 85, ErrorMessage = "enter the age between 25 and 85")]
        public int Age { get; set; }
        [Required]
        public int Speciality { get; set; }
        [Required]
        public int Hospital { get; set; }
        [Required]
        [RegularExpression(@"\d+\.?\d{1,2}", ErrorMessage = "ConsultationCharges Accept upto 2 decimal digits")]
        public decimal ConsultationCharges { get; set; }
    
        public virtual Hospital Hospital1 { get; set; }
        public virtual Speciality Speciality1 { get; set; }
    }
}
